# tasks file for virtualbox
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ virtualbox_dependencies }}"
  tags:
    - virtualbox-install-dependencies

- name: install
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ virtualbox_install }}"
  tags:
    - virtualbox-install-additional
